### ISSUE TITLE
Difficulty getting framework to properly render on development server from 0.0.0.0

### ISSUE THREAD

**Issue by anoduck** [nusserstudios/tailbliss#131]
I am developing my site on a remote server, so I need to be able to render the site on an address other than localhost. I have made the necessary changes to `packages.json` and added `--bind 0.0.0.0 -b ./ --disableFastRender`, yet still assets are referenced to localhost.

Is there a way to change this?

**Comment by nusserstudios** [comment]
I have never tried developing live on a remote site. Did you put the live domain in baseURL: ''?

**Comment by KhalilSecurity** [comment]
I use this command to develop on a remote server + VS code SSH plugin. No changes to package.json or hugo.yaml
```
sudo hugo server --bind 192.168.180.20 --baseURL http://192.168.180.20
```
Change 192.168.180.20 to your server IP

**Comment by anoduck** [comment]
@nusserstudios It does the same thing with every theme 

> I use this command to develop on a remote server + VS code SSH plugin. No changes to package.json or hugo.yaml
> 
> ```
> sudo hugo server --bind [192.168.180.20](http://192.168.180.20) --baseURL http://192.168.180.20
> ```
> 
> Change [192.168.180.20](http://192.168.180.20) to your server IP

I was using `-b ./`. That works.
