### ISSUE TITLE
Image processing

### ISSUE THREAD

**Issue by ElastiCourse** [nusserstudios/tailbliss#132]
Hi Jeremy,

Thanks for such great responsive theme. I'm about to submit a PR of some minor issues I found as I developed with this theme. 

I have some issues with image processing and paths. First, I noticed all images are pixelated and of lower quality in post content, featured image and even homepage p1,2,3.. etc images
[Example](https://www.elasticourse.com/how-to-install-gns3-network-emulation-software-in-windows-10-11/) 

Take `step 2` as example from the example. The original image in png format is 36kb
using imgc shortcode
{{< imgc src="gns3-platforms.png" alt="gns3-platforms" >}} 
 it produces webp version at 14.5kb but looks really bad. 
![imgc](https://github.com/nusserstudios/tailbliss/assets/71233127/0c735844-975a-4a10-8c40-7eebc642a433)

---
native image code
`![Stormtroopocat](/images/gns3-platforms.png "The Stormtroopocat")`
uses the original png 36kb, best quality
![native](https://github.com/nusserstudios/tailbliss/assets/71233127/c535fda7-d63b-4048-a099-f87aa69eb1a4)

---
native image code but using converted webp version using cloudconvert.com
`![Stormtroopocat](/images/gns3-platforms.webp "The Stormtroopocat")
`optimized webp is sized 17kb, shows much higher quality than the imgc, and slightly lower quality than png but still acceptable
![native-webp](https://github.com/nusserstudios/tailbliss/assets/71233127/aa2f3799-f177-4a23-8fca-804290948339)

do you have any suggestions?
---
My second question is regarding paths, I'm using the release that has `canonifyURLs: true`, I have a hard time understanding how paths work with multiple image folders

take sample blog posts as an example, 
authorimage: ../assets/images/global/author.webp WORKS
featured_image: /images/gns3.webp WORKS 
both the featured image and authorimage are in assets folder, but they are referenced in two different ways
from post point of view at tailbliss/content/posts/x.md
how could tailbliss/assets/images be referenced this way? I would have expected something like ../../assets/images/gns3.webp

then on the other hand the native image tag would only look in tailbliss/static/ then reference the internal path
`![Stormtroopocat](/images/gns3-platforms.png "The Stormtroopocat")
`
it also wouldn't support native image code for a file in the assets/images regardless
```
![Stormtroopocat](/assets/images/ova.jpg "The Stormtroopocat")
![Stormtroopocat](../assets/images/ova.jpg "The Stormtroopocat")
![Stormtroopocat](../../assets/images/ova.jpg "The Stormtroopocat")
```

Best,

**Comment by nusserstudios** [comment]
Use the static folder, you can serve them all up from that.

**Comment by ElastiCourse** [comment]
I experimented with native image tags but they also have their drawbacks, they don't fill the container and lineup as imgc does

How about featured image, can you skip processing for it somehow? as I mentioned if I try to load a featured image from static folder it never loads

**Comment by nusserstudios** [comment]
It would be pulling the conditional statements and just using an image tag that looks right at static and applying a class of w-full h-auto. Just make sure you export images the size of the container. I'm using Astro for my site, and it's very similar to Hugo in that respect. I ended up moving all my media to an S3 bucket that serves up all my media.
