### ISSUE TITLE
markdown-it support

### ISSUE THREAD

**Issue by pwab** [nusserstudios/tailbliss#134]
I have skimmed the [about page](https://tailbliss.netlify.app/about/) to see how the typography and markdown parsing is done. At the end of the page there are some markdown-it plugins mentioned with a sample text to demonstrate how they work. It seems that only some of the examples work (might be only footnotes) and the rest is not.

![grafik](https://github.com/nusserstudios/tailbliss/assets/19271185/437ce661-633d-468a-a656-9483221e415e)

Also the typographic replacements at the top of the page do not work.

![grafik](https://github.com/nusserstudios/tailbliss/assets/19271185/3a73472c-1f11-401a-a916-7c6a5a94975e)

I compared to the output of the markdown-it sample page at https://markdown-it.github.io/.

My questions are:

- Is this a bug or missing feature? Or are markdown-it plugins generally not supported?
    - If those plugins should be supported: Where to configure them? I'm not sure if this theme is using a specific markdown parser and how to change it accordingly.
    - If those plugins aren't and won't be supported: The only possibility to extend the markdown functionality is to configure the [hugo goldmark markup](https://gohugo.io/getting-started/configuration-markup/). Or am I missing something?

**Comment by nusserstudios** [comment]
They were working previously. I was using goldmark for markdown. This could be why, so it needs to be fixed.

**Comment by nusserstudios** [comment]
Looks like those have never worked from looking at the demo. I did test goldmark and it made no difference.
