### ISSUE TITLE
new list arrangement

### ISSUE THREAD

**Issue by Kevin75311** [nusserstudios/tailbliss#136]
Hi, thank you for the beautiful theme. I have played around with it and hope to make some modifications. Here is the layout structure as I understand it (though there might be some mistakes):
![image](https://github.com/nusserstudios/tailbliss/assets/59347832/03e30a9d-6267-47d1-a1e1-54d3465d44b6)
I'm unsure about where the 'home-hero.html' layout is used. Additionally, I would like to add another kind of list layout ('list2.html'), where the posts will occupy the whole row, like this (in your nusserstudios website):
![image](https://github.com/nusserstudios/tailbliss/assets/59347832/21675def-63f3-4976-8804-bb413cc28892)

I've already created the layout myself, but I'm not sure how to implement it into this theme. 
Could you kindly guide me on how to do so?
Thank you very much.

**Comment by nusserstudios** [comment]
That site is built on Astro, and AstroWind is the theme. You'll want to change the list file. Take a look at Hugo's [directory structure](https://gohugo.io/getting-started/directory-structure/).
