### ISSUE TITLE
I tried it on windows with npm 6.14.8 and got below errors

### ISSUE THREAD

**Issue by wnadim92** [nusserstudios/tailbliss#162]
`Start building sites … 
hugo v0.121.1-00b46fed8e47f7bb0a85d7cfc2d9f1356379b740+extended windows/amd64 BuildDate=2023-12-08T08:47:45Z VendorInfo=gohugoio

Total in 5237 ms
Error: error building site: POSTCSS: failed to transform "css/style.css" (text/css): (node:7480) ExperimentalWarning: The ESM module loader is experimental.
internal/process/esm_loader.js:90
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader. Received protocol 'node:'
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:730:11)
    at Loader.resolve (internal/modules/esm/loader.js:100:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:246:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:47:40)
    at link (internal/modules/esm/module_job.js:46:36) {
  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! TailBliss@0.1.1 build: `hugo --minify`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the TailBliss@0.1.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\wnadi\AppData\Roaming\npm-cache\_logs\2023-12-30T14_19_53_576Z-debug.log
PS A:\wnadi\Documents\Local-Study\VScode-bucket\idealcloudconsulting-8\site\themes\tailbliss> `

**Comment by nusserstudios** [comment]
That version of node is too far out of date. you need to be using at least V18, but 20 is the current. I'd recommend using WSL with a linux distro, and NVM if you need old versions. You cant use Tailwind with really old versions of node like that.
