### ISSUE TITLE
Some things don't work with Hugo 0.127 on Linux/Firefox

### ISSUE THREAD

**Issue by iandouglas** [nusserstudios/tailbliss#192]
I pulled your theme into a new Hugo site I'm making and "npm run start" executes just fine. Thanks for a great starter kit!!!

When viewing the "About" page to see the formatting render from Markdown to HTML, the following things don't work out of the box in Firefox on Linux (Ubuntu 24.04, Firefox 127.0.1). I see the same rendering problems on the demo site at https://tailbliss.netlify.app/about/ as well.

None of these convert:

`(c) (C) (r) (R) (tm) (TM) (p) (P) +-`
`!!!!!! ???? ,,`

For the Emojis, some of them work, some of them don't:

`Classic markup: 😉 :crush: 😢 :tear: 😆 😋`
`Shortcuts (emoticons): :-) :-( 8-) ;)`

Subscript / Superscript

`    19^th^`
`    H~2~O`

`<ins>`
`++Inserted text++`

`<mark>`
`==Marked text==`

Footnotes
`Inline footnote^[Text of inline footnote] definition.` renders exactly like this on the page

Abbreviations
None of this does the tooltip pop-up as described, it literally renders the `*[HTML]` text on the page
```
This is HTML abbreviation example.

It converts “HTML”, but keep intact partial entries like “xxxHTMLyyy” and so on.

*[HTML]: Hyper Text Markup Language
```

**Comment by iandouglas** [comment]
looks like the social icons at the bottom of the page don't render the links properly, either

there was also a deprecation warning in `layouts/partials/head.html` to change the `if` statement to `if hugo.IsServer`

**Comment by nusserstudios** [comment]
Yeah, I may pull that, honestly. I've looked into trying to fix it, but wasn't able to resolve it.
