### ISSUE TITLE
multilanguage support

### ISSUE THREAD

**Issue by Kwaskoff** [nusserstudios/tailbliss#79]
of course, we can use a clone of the site with a different language, but I think the language support inside the theme is better

**Comment by nusserstudios** [comment]
Most definitely. My apologies, I'm new to Hugo. I will see if I cant look at moving stuff into a theme. Its very developer oriented as well, especially the nav and such. If you're seasoned with Hugo and would like to help, I'd definitely appreciate any suggestions or best practices that we can move to.

**Comment by Kwaskoff** [comment]
unfortunately, I am not a developer, but I communicate with the author of this https://github.com/somratpro/somrat and you can spy on how he did
p.s. we use his theme on finteh.org and looking for something new

**Comment by nusserstudios** [comment]
I will get this fixed by next week. I'm really busy at the moment, but I'll get multi-lang added to the config file. I will close when complete.

**Comment by Kwaskoff** [comment]
> I will get this fixed by next week. I'm really busy at the moment, but I'll get multi-lang added to the config file. I will close when complete.

if it can be more useful for you - we can create kanban board here https://github.com/nusserstudios/tailbliss/projects?query=is%3Aopen with backlog
