### ISSUE TITLE
Documentation on images location

### ISSUE THREAD

**Issue by yuriizinets** [nusserstudios/tailbliss#85]
Can't figure out a proper images location.  
We have:
- images
- assets/images
- static/images
- resources/_gen/images (ok, this one we can exclude)

**Comment by nusserstudios** [comment]
Images are used in both static and assets. Static is mainly for SVG and native WEBP, while assets are images processed by Hugo Pipes. So the featured_image from frontmatter is processed by hugo pipes, while the header/nav would use the <img src="/images/site-logo.svg" class="transition-opacity h-9 w-9 group-hover:opacity-50 group-focus:opacity-70"  alt="{{ .Site.Title }} Logo" /> from static. Does that make sense? My apologies, but from what I could tell, that is the way Hugo is built. I would say, if you want to just use webp for your site, then just use static. If you do want to use PNG files, use them from assets, and add on the image processing to convert to webp.

**Comment by yuriizinets** [comment]
Makes sense, thank you! :)
