### ISSUE TITLE
Include non-theme content in build pipeline?

### ISSUE THREAD

**Issue by pehrlich2** [nusserstudios/tailbliss#95]
I found I had to add my non-theme html files to the build pipeline to get it working correctly:

```
# themes/tailbliss/tailwind.config.js
content: ['./layouts/**/*.html', './content/**/*.md', '../../layouts/**/*.html'],
```

as well as adding a blank `tailwind.config.js` in my root dir.  This allowed me to switch from indigo to another color, and have the css file correctly rebuild with the watch command.

**Comment by nusserstudios** [comment]
Gotcha, and thank you. Submit a pull request and I'll merge it.
