### ISSUE TITLE
Can't build site nor launch server

### ISSUE THREAD

**Issue by AlexandreLemoine40** [nusserstudios/tailbliss#96]
I downloaded the repository to a folder to make a website using this theme. I installed the node modules using `npm install` at the root of the project then I made `hugo server` and I have this output : 
![image](https://user-images.githubusercontent.com/47149440/217501163-7066edbc-639c-4aa6-838e-fd189db5cdc7.png)

It wasn't clear on the readme, but I saw I had to use `npm run start` to launch hugo server but I have this output :

![image](https://user-images.githubusercontent.com/47149440/217501432-bbf0a7d4-0f27-4098-bf6c-3cae0db2a291.png)

My OS is Debian 11 Bullseye
I'm using Node version 14.21.2 as I had problems with POSTCSS using Node 10
My NPM is v6.14.17 maybe I should upgrade it but I didn't try.
Hugo version : hugo v0.110.0

**Comment by AlexandreLemoine40** [comment]
Ok I solved the problem, I had to make a commit before using `hugo server`

**Comment by nusserstudios** [comment]
I know for sure it works with node ^16. I use NVM to switch between node 16-19. I don't use node below v16 at this point.
