### ISSUE TITLE
Can't access new HTML file created in the layouts folder

### ISSUE THREAD

**Issue by AlexandreLemoine40** [nusserstudios/tailbliss#97]
I created a new HTML static file `info.html`. I want it to be accessible at `/info/`
Here's the content of the file

```
{{ define "main" }}
<main>
    <header class="mb-4 bg-indigo-600">
        <span class="py-96">
            <h1 class="py-16 text-5xl font-black text-center text-white capitalize">
                Calculateur de 1 RM
            </h1>
        </span>
    </header>
    <div class="max-w-4xl mx-auto mt-8 mb-2">
        <div class="px-6">
            <label for="poids">Poids</label>
            <input name="poids" id="poids" type="number">
            <label for="repetitions"></label>
            <input name="repetitions" id="repetitions" type="number">
            <button id="calculer">Calculer</button>
        </div>
    </div>
    <!-- " {{.Content}}" pulls from the markdown content of the corresponding _index.md -->
    <div class="max-w-2xl px-6 pt-6 pb-16 mx-auto prose dark:prose-invert dark:text-white">
        {{.Content}}
    </div>
</main>
{{ end }}
```

But when I launch `hugo server` there's no new page generated 
![image](https://user-images.githubusercontent.com/47149440/217858578-3999d13b-0598-46ea-841a-2637c6f5133f.png)

Layouts folder content : 
![image](https://user-images.githubusercontent.com/47149440/217858826-c182c1f1-b858-4e79-8859-32faac1df1f7.png)

I'm not using TailbLiss as a theme but it is the root of my hugo site.

If there is a way to make new HTML pages accessible right after the `/` let me know it would help me a lot, thanks.

**Comment by nusserstudios** [comment]
It needs to be referenced in your front matter like this:
**type: "info"
layout: infolayout"**

You'll also need an info.md in /content/pages or /content/wherever-you-want.

**Comment by AlexandreLemoine40** [comment]
What file I need to add the type and the layout name in ?

**Comment by AlexandreLemoine40** [comment]
Tanks a lot
